purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6899298212956637
  brandStrength: 1
  lightness: 0.4851138214580715
  brandColors:
    - '#FFFFFF'
    - '#BBDD00'
    - '#7F7F7F'
    - '#D7EB7C'
    - '#191919'
  rhythmicContrast: 0.5018952144309878
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: RIZOM
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9966083450708538
layout_spectrum: 0.3240782527718693
