name: RIZOM
favicon: null
layout_spectrum: 0.3240782527718693
typography_spectrum: 0.9966083450708538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7382901343517005
  lightness: 0.48511382145807147
  saturation: 0.6899298212956637
  rhythmicContrast: 0.5018952144309878
purpose: []
